# Generated by Django 5.2.6 on 2025-09-17 09:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('image', 0)], block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {})}, default=dict),
            preserve_default=False,
        ),
    ]
